### PR TITLE
Update urllib

### PR DESCRIPTION
**Pull request by bonnee**
Fixes this library for me

### CODE REVIEW

**Comment by hroncok** [comment]
Hello. Thanks for your fix, however, I am not interested in maintaining this project anymore. Do you want me to transfer it to you?

**Comment by bonnee** [comment]
Yes! I'll be happy to keep it working

**Comment by hroncok** [comment]
Could you please rename your fork?

**Comment by bonnee** [comment]
Done!

**Comment by hroncok** [comment]
It appears you need to delete it entirely :/

**Comment by bonnee** [comment]
Makes sense. Done it

**Pull request merged**
